name: bip39_mnemonic
description:  Mnemonic code for generating deterministic keys a.k.a. BIP39.
version: 2.0.0
homepage: https://github.com/ethicnology/dart-bip39-mnemonic

environment:
  sdk: '>=2.16.1 <3.0.0'
dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
  convert: ^3.0.1
dependencies: 
  pointycastle: ^3.5.2
  unorm_dart: ^0.2.0
